version: '3.8'

services:
  nodejs-app:
    container_name: nodejs-app
    build:
      context: ./nodejs-app
    ports:
      - "4000:4000"
    volumes:
      - nodejs-data:/app/node_modules
    networks:
      - app-network

  react-app:
    container_name: react-app
    build:
      context: ./react-app
    ports:
      - "3000:3000"
    volumes:
      - react-data:/app/node_modules
    networks:
      - app-network
    depends_on:
      - nodejs-app

networks:
  app-network:
    driver: bridge

volumes:
  nodejs-data:
  react-data:
